-- Version 0.1

SET NAMES utf8mb4;
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

DROP SCHEMA IF EXISTS jader;
CREATE SCHEMA jader;
USE jader;

--
-- demo
--

CREATE TABLE demo (
  id VARCHAR(45) NOT NULL,
  num VARCHAR(45) NOT NULL,
  sex VARCHAR(45) NOT NULL,
  age VARCHAR(45) NOT NULL,
  weight VARCHAR(45) DEFAULT NULL,
  hight VARCHAR(45) DEFAULT NULL,
  time VARCHAR(45) NOT NULL,
  status VARCHAR(45) NOT NULL,
  type VARCHAR(45) NOT NULL,
  lice VARCHAR(45) DEFAULT NULL,
  ver VARCHAR(45) NOT NULL,
  PRIMARY KEY (id),
  KEY idx_deid (id)
) ENGINE=InnoDB DEFAULT CHARSET=sjis;


--
-- drug
--

CREATE TABLE drug (
  id VARCHAR(45) NOT NULL,
  num VARCHAR(45) NOT NULL,
  drug_serl VARCHAR(45) NOT NULL,
  drug_type VARCHAR(45) NOT NULL,
  gen_name VARCHAR(1024) DEFAULT NULL,
  bland_name VARCHAR(45) DEFAULT NULL,
  route VARCHAR(1024) DEFAULT NULL,
  start_date VARCHAR(1024) DEFAULT NULL,
  end_date VARCHAR(1024) DEFAULT NULL,
  amount VARCHAR(1024) DEFAULT NULL,
  tani VARCHAR(1024) DEFAULT NULL,
  times VARCHAR(1024) DEFAULT NULL,
  object VARCHAR(1024) DEFAULT NULL,
  response VARCHAR(45) DEFAULT NULL,
  react VARCHAR(1024) DEFAULT NULL,
  bunrui VARCHAR(45) DEFAULT NULL,
  PRIMARY KEY (id, drug_serl),
  KEY idx_drid (id)
) ENGINE=InnoDB DEFAULT CHARSET=sjis;

--
-- reac
--

CREATE TABLE reac (
  id VARCHAR(45) NOT NULL,
  num VARCHAR(45) NOT NULL,
  reac_serl VARCHAR(45) NOT NULL,
  reac VARCHAR(45) DEFAULT NULL,
  outcome VARCHAR(45) DEFAULT NULL,
  reac_date VARCHAR(45) DEFAULT NULL,
  PRIMARY KEY (id, reac_serl),
  KEY idx_reid (id)
) ENGINE=InnoDB DEFAULT CHARSET=sjis;

--
-- hist
--

CREATE TABLE hist (
  id VARCHAR(45) NOT NULL, 
  num VARCHAR(45) NOT NULL,
  hist_serl VARCHAR(45) NOT NULL,
  hist VARCHAR(45) DEFAULT NULL,
  PRIMARY KEY (id, hist_serl),
  KEY idx_hiid (id)
) ENGINE=InnoDB DEFAULT CHARSET=sjis;
